export const skillset = [
    { id: 1, content: "Semantic & accessible HTML"},
    { id: 2, content: "Responsive Web Design"},
    { id: 3, content: "Teamwork"},
    { id: 4, content: "Markdown"},
    { id: 5, content: "Immutability"},
    { id: 6, content: "CSS BEM convention"},
    { id: 7, content: "CSS Grid"},
    { id: 8, content: "CSS Flexbox"},
    { id: 9, content: "React Router"},
    { id: 10, content: "Redux-Saga"},
    { id: 11, content: "Redux (Toolkit"},
    { id: 12, content: "React Hooks"},
    { id: 13, content: "Error handling"},
    { id: 14, content: "Working with API (fetch, axios"},
    { id: 15, content: "Java Script: ES6+"},
    { id: 16, content: "Promises, Async/Await"},
    { id: 17, content: "GitHub PullRequests & Review"},
    { id: 18, content: "Trello"},
    { id: 19, content: "NPM"},
    { id: 20, content: "React"},
    { id: 21, content: "Git"},
];